### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by malithsen** [heysulo/ucsc-results-center#27]
#### Feature request:
Send email when new results become available? Or some other form of notification which can be toggled through settings

**Comment by heysulo** [comment]
This feature is currently implemented using Facebook Messenger platform and stuck here. Facebook only provide individual verification for few countries. Sri Lanka is still not there
![image](https://user-images.githubusercontent.com/12120712/49688650-47bcd500-fb3b-11e8-9aa9-a82d31a96c56.png)

**Comment by malithsen** [comment]
Ah too bad. Maybe something like this? https://github.com/Schmavery/facebook-chat-api

But it probably violates Facebook ToS.

**Comment by heysulo** [comment]
Lets keep that as the backup plan if the review never git accepted
